cells = [
    [True , True , True , True , True , True , True , False, None , None , None , None , None , None , None , None , None , True , True ],
    [True , False, False, False, False, False, True , False, None , None , None , None , None , None , None , None , None , None , True ],
    [True , False, True , True , True , False, True , False, None , None , None , None , None , None , None , None , None , None , None ],
    [True , False, True , True , True , False, True , False, None , None , None , None , None , None , None , None , None , None , None ],
    [True , False, True , True , True , False, True , False, None , None , None , None , None , None , None , None , None , None , None ],
    [True , False, False, False, False, False, True , False, None , None , None , None , None , None , None , None , None , None , None ],
    [True , True , True , True , True , True , True , False, None , None , None , None , None , None , None , None , None , None , None ],
    [False, False, False, False, False, False, False, False, None , None , None , None , None , None , None , None , None , None , None ],
    [None , None , None , None , None , None , True , None , None , None , None , None , None , None , None , None , None , None , None ],
    [None , None , None , None , None , None , False, None , None , None , None , None , None , None , None , None , None , None , None ],
    [None , None , None , None , None , None , True , None , None , None , None , None , None , None , None , None , None , None , None ],
    [False, False, False, False, False, False, False, False, None , None , None , False, False, False, False, False, False, False, False],
    [True , True , True , True , True , True , True , False, True , False, True , False, True , True , True , True , True , True , True ],
    [True , False, False, False, False, False, True , False, None , None , None , False, True , False, False, False, False, False, True ],
    [True , False, True , True , True , False, True , False, None , None , None , False, True , False, True , True , True , False, True ],
    [True , False, True , True , True , False, True , False, None , None , None , False, True , False, True , True , True , False, True ],
    [True , False, True , True , True , False, True , False, None , None , None , False, True , False, True , True , True , False, True ],
    [True , False, False, False, False, False, True , False, None , None , None , False, True , False, False, False, False, False, True ],
    [True , True , True , True , True , True , True , False, None , None , None , False, True , True , True , True , True , True , True ],
]
